### PR TITLE
Fixes #30

### LINKED ISSUE #30: Add selection highlighting to editor
Highlight associated items in data browsers when mappings are selected, and vice-versa

### PR DESCRIPTION
**Pull request by jpav**

### CODE REVIEW

**Comment by kcbabo** [comment]
Works now.  One thing I noticed is that the asterisks next to mapped fields are missing now.

**Comment by kcbabo** [comment]
Another thing I noticed is that any change to the mapping requires the camel context path.  We used to only prompt for this on a change which required us to edit the camel configuration.

**Comment by kcbabo** [comment]
The show/hide mapped fields filter is broken.  It just hides everything now.

**Comment by kcbabo** [comment]
There's a regression in the custom mapping browser where it's looking at the test class path again.  We want this to use compile path only.

**Comment by kcbabo** [comment]
Seeing an issue with new Fuse Transformation wizard as well.  Once I click Finish, I get:
```
java.io.FileNotFoundException: /private/tmp/map-0/META-INF/spring/camel-context.xml (No such file or directory)
```
The issue here is that the path is not prefixed with src/main/resources.  We don't show this path to the user, but you need to prefix the path to resolve it within the project.

I'm going to stop testing now.  Once these are addressed, I would maybe try and walk through building the map-3 example app starting at map-0.  I think that would catch these and anything else common.

**Comment by jpav** [comment]
Damn,  I noticed that too and forgot to fix it.

**Comment by jpav** [comment]
I probably mucked this up.  Can you expound on what kind of change requires a Camel edit and what doesn't?

**Comment by kcbabo** [comment]
Sure.  I should have mentioned that in my comment.  The only time we touch the camel config in the mapper editor is when the source or target models are changed. That requires an update to the dozer endpoint in the camel config.

**Pull request closed without merging**
