### PR TITLE
Fixes #103

### LINKED ISSUE #103: Reorganize inner components of editor to have sensible structures and names
Also remove global and context menu delete capabilities since we now have a local toolbar button for that

### PR DESCRIPTION
**Pull request by jpav**

### CODE REVIEW

**Comment by kcbabo** [comment]
Not sure if this is due to 103 or a prior commit, but I get an empty editor when pulling up the map-2 dozerBeanMapping.xml with a build of your 103 branch.  Here's the associated error:

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.ClassCastException: org.eclipse.jface.layout.GridDataFactory cannot be cast to org.eclipse.swt.layout.GridData)
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.ClassCastException: org.eclipse.jface.layout.GridDataFactory cannot be cast to org.eclipse.swt.layout.GridData
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:208)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:197)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1201)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:710)
	at org.eclipse.swt.custom.CTabFolder.runUpdate(CTabFolder.java:3755)
	at org.eclipse.swt.custom.CTabFolder$10.run(CTabFolder.java:3741)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 24 more

**Comment by kcbabo** [comment]
I actually get the same error on master.  Are you able to open the config in examples/map-2 with the latest changes to the editor?

**Comment by jpav** [comment]
Not sure what’s happening to you with master.  That change was only introduced with 103.  It’s fixed now in the PR.

**Comment by kcbabo** [comment]
Looks like the merge got ugly when trying to fix this on your branch - it’s three commits now and can’t be rebased cleanly on top of master:

https://github.com/jpav/data-mapper/commits/103

~ keith

**Comment by kcbabo** [comment]
Forgot to mention that I built the changeset and it works great. :-)  If the git surgery is too nasty, you can always open a new branch off of master and then just copy your changed files to that new branch.  The diff will end up being the same.

**Comment by jpav** [comment]
I got it cleaned up and did the push to master

**Comment by kcbabo** [comment]
This has been pushed - closing the PR.

**Pull request closed without merging**
