### PR TITLE
Addresses as much of issue #81 as I can without issue #82 being complete

### PR DESCRIPTION
**Pull request by jpav**

### CODE REVIEW

**Comment by kcbabo** [comment]
I'm close on #82.  I have the constant capability working at runtime and I was able to handle it completely within the Dozer config, which is a nice win.  Just finishing up the extra methods you'll need in ConfigBuilder to hook up the tooling.

BTW, I need to make a major pass through core and abstract away some lower level, Dozer-ish details in m2.  I'm going to have to change it a bit for the constant stuff and we'll want to change some more for the custom field-level mappings.  I will try not to be too aggressive, but I do want to clean the API up a bit so it can handle all these cases a bit nicer.

**Comment by kcbabo** [comment]
These updates will also include a much easier way to correlate mapping operations to nodes in the source and target models.

**Comment by jpav** [comment]
I noticed a bug with the add source/target button being displayed even though a source/target has already been set.  I'll fix this in the final checkin.

**Comment by kcbabo** [comment]
Sounds good.  I will update my PR and push it as it touched a few lines in the Eclipse plugin.

BTW, can we avoid using the "Merge Pull Request" button?  I'm not a fan of how that thing litters history with merge commits.

**Comment by jpav** [comment]
Oh, right, forgot about that.

**Pull request merged**
